server:
  port: 80
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=PostgreSQL

  jpa:
      show-sql: false
      hibernate:
        ddl-auto: create
      properties:
          hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
          hibernate.format_sql: true